-- MySQL Script generated by MySQL Workbench
-- Mon Aug  3 15:17:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LibraryDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LibraryDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LibraryDatabase` DEFAULT CHARACTER SET utf8 ;
USE `LibraryDatabase` ;

-- -----------------------------------------------------
-- Table `LibraryDatabase`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryDatabase`.`book` ;

CREATE TABLE IF NOT EXISTS `LibraryDatabase`.`book` (
  `idbook` INT NOT NULL AUTO_INCREMENT,
  `bookName` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `publisher` VARCHAR(45) NOT NULL,
  `donated` VARCHAR(45) NOT NULL,
  `quantity` INT ZEROFILL NOT NULL,
  UNIQUE INDEX `idbook_UNIQUE` (`idbook` ASC) VISIBLE,
  PRIMARY KEY (`isbn`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDatabase`.`booksInStock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryDatabase`.`booksInStock` ;

CREATE TABLE IF NOT EXISTS `LibraryDatabase`.`booksInStock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(45) NULL,
  `booksInStock` INT NOT NULL,
  UNIQUE INDEX `iid_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`isbn`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE,
  INDEX `booksInStock_idx` (`booksInStock` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDatabase`.`donated`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryDatabase`.`donated` ;

CREATE TABLE IF NOT EXISTS `LibraryDatabase`.`donated` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `cms_id` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`isbn`, `cms_id`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE,
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC) VISIBLE,
  INDEX `cms_id_idx` (`cms_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDatabase`.`issuedBook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryDatabase`.`issuedBook` ;

CREATE TABLE IF NOT EXISTS `LibraryDatabase`.`issuedBook` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cms_id` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`cms_id`, `isbn`),
  UNIQUE INDEX `cms_id_UNIQUE` (`cms_id` ASC) VISIBLE,
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDatabase`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryDatabase`.`login` ;

CREATE TABLE IF NOT EXISTS `LibraryDatabase`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDatabase`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryDatabase`.`student` ;

CREATE TABLE IF NOT EXISTS `LibraryDatabase`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cms_id` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `fatherName` VARCHAR(45) NOT NULL,
  `department` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cms_id_UNIQUE` (`cms_id` ASC) VISIBLE,
  PRIMARY KEY (`cms_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDatabase`.`userDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryDatabase`.`userDetails` ;

CREATE TABLE IF NOT EXISTS `LibraryDatabase`.`userDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `jobStatus` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;

USE `LibraryDatabase` ;

-- -----------------------------------------------------
-- Placeholder table for view `LibraryDatabase`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryDatabase`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `LibraryDatabase`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryDatabase`.`view1`;
DROP VIEW IF EXISTS `LibraryDatabase`.`view1` ;
USE `LibraryDatabase`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `LibraryDatabase`.`book`
-- -----------------------------------------------------
START TRANSACTION;
USE `LibraryDatabase`;
INSERT INTO `LibraryDatabase`.`book` (`idbook`, `bookName`, `isbn`, `author`, `publisher`, `donated`, `quantity`) VALUES (1, 'Junior Level Books Introduction to Computer', '978-93-5019-561-1', 'Amit Garg', 'Reader\'s Zone', 'yes', 5);
INSERT INTO `LibraryDatabase`.`book` (`idbook`, `bookName`, `isbn`, `author`, `publisher`, `donated`, `quantity`) VALUES (2, 'Publish News Letter', '978-93-5019-561-2', 'Amit Garg', 'MCA Department, MIET Meerut', 'no', 9);
INSERT INTO `LibraryDatabase`.`book` (`idbook`, `bookName`, `isbn`, `author`, `publisher`, `donated`, `quantity`) VALUES (3, 'Client Server Computing', '978-93-8067-432-2', 'Lalit Kumar', 'Sun India Publications, New Delhi', 'no', 15);
INSERT INTO `LibraryDatabase`.`book` (`idbook`, `bookName`, `isbn`, `author`, `publisher`, `donated`, `quantity`) VALUES (4, 'Data Structure Using C', '978-93-5163-389-1', 'Sharad Kumar Verma', ' Thakur Publications Lucknow ', 'no', 12);
INSERT INTO `LibraryDatabase`.`book` (`idbook`, `bookName`, `isbn`, `author`, `publisher`, `donated`, `quantity`) VALUES (5, 'Computer Networks', '978-93-5163-389-5', 'Sharad Kumar Verma', 'Sun India Publications, New Delhi', 'yes', 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `LibraryDatabase`.`booksInStock`
-- -----------------------------------------------------
START TRANSACTION;
USE `LibraryDatabase`;
INSERT INTO `LibraryDatabase`.`booksInStock` (`id`, `isbn`, `booksInStock`) VALUES (1, '978-93-5019-561-1', 5);
INSERT INTO `LibraryDatabase`.`booksInStock` (`id`, `isbn`, `booksInStock`) VALUES (2, '978-93-5019-561-2', 9);
INSERT INTO `LibraryDatabase`.`booksInStock` (`id`, `isbn`, `booksInStock`) VALUES (3, '978-93-8067-432-2', 15);
INSERT INTO `LibraryDatabase`.`booksInStock` (`id`, `isbn`, `booksInStock`) VALUES (4, '978-93-5163-389-1', 12);
INSERT INTO `LibraryDatabase`.`booksInStock` (`id`, `isbn`, `booksInStock`) VALUES (5, '978-93-5163-389-5', 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `LibraryDatabase`.`donated`
-- -----------------------------------------------------
START TRANSACTION;
USE `LibraryDatabase`;
INSERT INTO `LibraryDatabase`.`donated` (`id`, `isbn`, `firstName`, `lastName`, `phoneNumber`, `cms_id`) VALUES (1, '978-93-5019-561-1', 'Waqar', 'Rao', '03333834354', '023-16-0026');
INSERT INTO `LibraryDatabase`.`donated` (`id`, `isbn`, `firstName`, `lastName`, `phoneNumber`, `cms_id`) VALUES (2, '978-93-5163-389-5', 'Saima', 'Sajjad', '03333245123', '023-16-0029');

COMMIT;


-- -----------------------------------------------------
-- Data for table `LibraryDatabase`.`login`
-- -----------------------------------------------------
START TRANSACTION;
USE `LibraryDatabase`;
INSERT INTO `LibraryDatabase`.`login` (`id`, `username`, `password`) VALUES (1, 'waqar354', '12345');
INSERT INTO `LibraryDatabase`.`login` (`id`, `username`, `password`) VALUES (2, 'saima', 'sajjad');

COMMIT;


-- -----------------------------------------------------
-- Data for table `LibraryDatabase`.`student`
-- -----------------------------------------------------
START TRANSACTION;
USE `LibraryDatabase`;
INSERT INTO `LibraryDatabase`.`student` (`id`, `cms_id`, `firstName`, `lastName`, `fatherName`, `department`) VALUES (1, '023-16-0026', 'Waqar', 'Rao', 'Rao Liaquat Ali', 'cs');
INSERT INTO `LibraryDatabase`.`student` (`id`, `cms_id`, `firstName`, `lastName`, `fatherName`, `department`) VALUES (2, '023-16-0029', 'Saima', 'Sajjad', 'Sajjad Ali', 'cs');

COMMIT;


-- -----------------------------------------------------
-- Data for table `LibraryDatabase`.`userDetails`
-- -----------------------------------------------------
START TRANSACTION;
USE `LibraryDatabase`;
INSERT INTO `LibraryDatabase`.`userDetails` (`id`, `username`, `firstName`, `lastName`, `jobStatus`, `phoneNumber`) VALUES (1, 'waqar354', 'Waqar', 'Rao', 'Librarian', '03333834354');
INSERT INTO `LibraryDatabase`.`userDetails` (`id`, `username`, `firstName`, `lastName`, `jobStatus`, `phoneNumber`) VALUES (2, 'saima', 'Saima', 'Sajjad', 'Librarian', '03333535135');

COMMIT;

